#!/usr/bin/env python3
# _gen_notes_site.py — 为 mkdocs 预览生成"需求 (进行中)"导航
#
# 行为:
#   1. 扫描 docs/requirements/*.md (不含 finished/ 子目录)
#   2. 在 notes/requirements/ 下建立对每个文件的符号链接 (清理过期链接)
#   3. 读取 mkdocs.yml -> 注入 nav 段 + watch 段 -> 写出 mkdocs.gen.yml
#
# 由 scripts/serve-notes.sh 调用。

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
REQ_SRC_DIR = REPO_ROOT / "docs" / "requirements"
NOTES_DIR = REPO_ROOT / "notes"
REQ_LINK_DIR = NOTES_DIR / "requirements"
MKDOCS_SRC = REPO_ROOT / "mkdocs.yml"
MKDOCS_GEN = REPO_ROOT / "mkdocs.gen.yml"

NAV_SECTION_TITLE = "需求 (进行中)"
HEADING_RE = re.compile(r"^#\s+(.+?)\s*$")


def discover_requirements() -> list[Path]:
    if not REQ_SRC_DIR.is_dir():
        return []
    files = [p for p in REQ_SRC_DIR.iterdir() if p.is_file() and p.suffix == ".md"]
    files.sort(key=lambda p: p.name)
    return files


def extract_title(md_path: Path, fallback: str) -> str:
    try:
        with md_path.open("r", encoding="utf-8") as f:
            for line in f:
                m = HEADING_RE.match(line)
                if m:
                    return m.group(1)
    except OSError:
        pass
    return fallback


def sync_symlinks(req_files: list[Path]) -> None:
    REQ_LINK_DIR.mkdir(parents=True, exist_ok=True)

    wanted = {p.name for p in req_files}

    for entry in REQ_LINK_DIR.iterdir():
        if entry.is_symlink() or entry.is_file():
            if entry.name not in wanted or entry.name == "index.md":
                if entry.name != "index.md":
                    entry.unlink()

    for src in req_files:
        link = REQ_LINK_DIR / src.name
        target = os.path.relpath(src, REQ_LINK_DIR)
        if link.is_symlink() or link.exists():
            try:
                if link.is_symlink() and os.readlink(link) == target:
                    continue
            except OSError:
                pass
            link.unlink()
        link.symlink_to(target)

    write_index(req_files)


def write_index(req_files: list[Path]) -> None:
    index_path = REQ_LINK_DIR / "index.md"
    lines = [
        "# 需求 (进行中)",
        "",
        "本目录由 `scripts/_gen_notes_site.py` 自动生成，列出 `docs/requirements/` 下尚未归档的需求文档。",
        "",
    ]
    for p in req_files:
        title = extract_title(p, p.stem)
        lines.append(f"- [{title}]({p.name})")
    lines.append("")
    index_path.write_text("\n".join(lines), encoding="utf-8")


def build_nav_section(req_files: list[Path]) -> dict:
    entries: list = ["requirements/index.md"]
    for p in req_files:
        title = extract_title(p, p.stem)
        entries.append({title: f"requirements/{p.name}"})
    return {NAV_SECTION_TITLE: entries}


def inject_into_mkdocs(req_files: list[Path]) -> None:
    with MKDOCS_SRC.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    nav = cfg.get("nav") or []
    nav = [item for item in nav if not (isinstance(item, dict) and NAV_SECTION_TITLE in item)]

    if req_files:
        nav.append(build_nav_section(req_files))

    cfg["nav"] = nav

    watch = cfg.get("watch") or []
    rel_req = os.path.relpath(REQ_SRC_DIR, REPO_ROOT)
    if rel_req not in watch:
        watch.append(rel_req)
    cfg["watch"] = watch

    hooks = cfg.get("hooks") or []
    hook_path = "scripts/_notes_hooks.py"
    if hook_path not in hooks:
        hooks.append(hook_path)
    cfg["hooks"] = hooks

    header = (
        "# AUTO-GENERATED by scripts/_gen_notes_site.py — DO NOT EDIT.\n"
        "# Source: mkdocs.yml + docs/requirements/*.md\n"
    )
    with MKDOCS_GEN.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False)


def main() -> int:
    if not MKDOCS_SRC.is_file():
        print(f"Error: {MKDOCS_SRC} not found", file=sys.stderr)
        return 1

    req_files = discover_requirements()
    sync_symlinks(req_files)
    inject_into_mkdocs(req_files)

    print(f">> Generated {MKDOCS_GEN.relative_to(REPO_ROOT)}")
    print(f"   {NAV_SECTION_TITLE}: {len(req_files)} 篇")
    for p in req_files:
        print(f"     - {p.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
